version: '3.8'

services:
  backend:
    image: hernandodiaz20/tecnofix-backend:latest
    ports:
      - "3000:3000"
    # Descomenta y ajusta las variables de entorno si el backend las necesita para conectarse a la base de datos:
    # environment:
    #   - PORT=3000
    #   - DATABASE_URL=tu_url_de_base_de_datos

  frontend:
    image: hernandodiaz20/tecnofix-frontend:latest
    ports:
      - "8080:80"
    depends_on:
      - backend
